name: SoapUI API test

on: 
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            soapui-projectfile-location: /src/test/soapui
            soapui-projectfile-name: /project/AvansTestSuite.xml
        steps:
        - uses: actions/checkout@v3
        # - uses: addnab/docker-run-action@v3
        #   with:
        #     image: smartbear/soapuios-testrunner
        #     options: -v=${{ github.workspace }}${{ env.soapui-projectfile-location }}:/project --entrypoint /bin/bash
        #     run: |
        #         ./$SOAPUI_DIR/bin/testrunner.sh ${{ env.soapui-projectfile-name }}

        - name: Install Neoload CLI
          run: pip3 install -U neoload

        - name: "Prepare NeoLoad test"
          run: >
                neoload login --url https://neoload-api.saas.neotys.com/ 579d0fd1ebc40b7fe1d0af8dc8d0cea9ec29fe914b67edea \
                        test-settings --zone "Europe Germany (Frankfurt 3)" --scenario 'HappyFlow' createorpatch "My Github Test With CLI 2" \
                        project --path ${{ github.workspace }}/demowebshopp.zip upload
            
        - name: Run Neoload test
          run: neoload run --name "My Github Test With CLI 2"
            
        - name: "Generate Test Report"
          run: neoload test-results junitsla
    
        - name: "Publish Test Report"
          if: ${{ always() }}
          uses: scacap/action-surefire-report@v1
          with:
            report_paths: junit-sla.xml
            fail_on_test_failures: true