name: SoapUI API test

on: 
    workflow_dispatch:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SOAPUI_PROJECT_DIR: /src/test/soapui
            SOAPUI_PROJECT_FILE: AvansTestSuite-soapui-project.xml
        steps:
        - uses: addnab/docker-run-action@v3
          with:
            image: smartbear/soapuios-testrunner