name: SoapUI API test

on: 
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: addnab/docker-run-action@v3
          with:
            image: smartbear/soapuios-testrunner
            options: -v=${{ github.workspace }}/src/test/soapui:/project -i --entrypoint /bin/bash
            run: |
                ./$SOAPUI_DIR/bin/testrunner.sh /project/avanstestsuite.xml