name: SoapUI API test

on: 
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            soapui-projectfile-location: /src/test/soapui
            soapui-projectfile-name: /project/avanstestsuite.xml
        steps:
        - uses: actions/checkout@v3
        - uses: addnab/docker-run-action@v3
          with:
            image: smartbear/soapuios-testrunner
            options: -v=${{ github.workspace }}${{ env.soapui-projectfile-location }}:/project --entrypoint /bin/bash
            run: |
                ./$SOAPUI_DIR/bin/testrunner.sh ${{ env.soapui-projectfile-name }}