name: SoapUI API test

on: 
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: addnab/docker-run-action@v3
          with:
            image: smartbear/soapuios-testrunner
            options: -e COMMAND_LINE="'/%project%/avanstestsuite.xml'" -i echo $?
            run: |
                echo $?