name: SoapUI API test

on: 
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: addnab/docker-run-action@v3
          with:
            image: smartbear/soapuios-testrunner
            options: -v=/src/test/soapui:/project -v=/src/test/soapui:/reports -e COMMAND_LINE="-f/%reports% '/%project%/AvansTestSuite-soapui-project.xml'" -i 
            run: |
                echo $?